// // import nodemailer from "nodemailer";
// // import { env } from "../config/env.js";

// // const transporter = nodemailer.createTransport({
// //   service: "gmail", // or your SMTP provider
// //   auth: {
// //     user: env.emailUser, 
// //     pass: env.emailPass,
    
// //   },
// // });

// // export const sendResetEmail = async (to, token) => {
// //   const resetUrl = `http://localhost:5173/reset-password?token=${token}`; // Adjust for your frontend URL
// //   const mailOptions = {
// //     from: env.emailUser,
// //     to,
// //     subject: "Password Reset Token",
// //     html: `<p>You requested a password reset. Use the token below or click the link:</p>
// //            <h3>${token}</h3>
// //            <a href="${resetUrl}">Reset Password</a>
// //            <p>This token expires in 15 minutes.</p>`,
// //   };

// //   await transporter.sendMail(mailOptions);
// // };




// import nodemailer from "nodemailer";
// import { env } from "../config/env.js";

// /**
//  * Configure Transporter
//  * Using Port 587 with STARTTLS is more reliable on cloud platforms like Render.
//  * Ensure env.emailPass is a 16-character Google App Password.
//  */
// const transporter = nodemailer.createTransport({
//   host: "smtp.gmail.com",
//   port: 587,
//   secure: false, // Must be false for port 587
//   auth: {
//     user: env.emailUser,
//     pass: env.emailPass, 
//   },
//   tls: {
//     // Helps bypass cloud network restrictions/self-signed certificate issues
//     rejectUnauthorized: false 
//   }
// });

// /**
//  * Sends a password reset email to the user.
//  * @param {string} to - Recipient email address.
//  * @param {string} token - The reset token generated by crypto.
//  */
// export const sendResetEmail = async (to, token) => {
//   // Pulls the live Vercel URL from your environment configuration
//   const resetUrl = `${env.frontendUrl}/reset-password?token=${token}`; 

//   const mailOptions = {
//     from: env.emailUser,
//     to,
//     subject: "Password Reset Token - MKM Inventory",
//     html: `
//       <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: auto; border: 1px solid #ddd; padding: 20px; border-radius: 10px;">
//         <h2 style="color: #007bff; text-align: center;">MKM Inventory System</h2>
//         <hr>
//         <p>Hello,</p>
//         <p>You requested a password reset. Please use the token below to complete the process:</p>
//         <div style="text-align: center; margin: 20px 0;">
//           <h2 style="background: #f4f4f4; padding: 15px; letter-spacing: 5px; display: inline-block; border-radius: 5px;">${token}</h2>
//         </div>
//         <p>Alternatively, you can click the button below to reset your password directly:</p>
//         <div style="text-align: center; margin: 30px 0;">
//           <a href="${resetUrl}" style="background: #007bff; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold;">Reset Password</a>
//         </div>
//         <p style="font-size: 0.9em; color: #666;">This link and token will expire in <strong>15 minutes</strong>. If you did not request this, please ignore this email.</p>
//         <hr>
//         <p style="font-size: 0.8em; color: #999; text-align: center;">MKM Montessori ERP - Automated System</p>
//       </div>`
//   };

//   try {
//     await transporter.sendMail(mailOptions);
//     console.log(`Reset email sent successfully to ${to}`);
//   } catch (error) {
//     console.error("Nodemailer Error details:", error);
//     throw new Error("Failed to send reset email.");
//   }
// };











// utils/mailer.js
import nodemailer from "nodemailer";
import { env } from "../config/env.js";

const transporter = nodemailer.createTransport({
  service: "gmail", // Use the built-in 'gmail' service helper
  host: "smtp.gmail.com",
  port: 465,
  secure: true, // Port 465 requires secure: true
  auth: {
    user: env.emailUser,
    pass: env.emailPass, 
  },
  tls: {
    rejectUnauthorized: false // Bypasses the ENETUNREACH/Cert issues
  }
});

export const sendResetEmail = async (to, token) => {
  const resetUrl = `${env.frontendUrl}/reset-password?token=${token}`; 

  const mailOptions = {
    from: `"MKM Admin" <${env.emailUser}>`, // Added formal display name
    to,
    subject: "Password Reset Token - MKM Inventory",
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #ddd; padding: 20px; border-radius: 10px;">
        <h2 style="color: #007bff; text-align: center;">MKM Inventory System</h2>
        <hr>
        <p>You requested a password reset. Please use the token below:</p>
        <div style="text-align: center; margin: 20px 0;">
          <h2 style="background: #f4f4f4; padding: 15px; letter-spacing: 5px; display: inline-block; border-radius: 5px;">${token}</h2>
        </div>
        <p>Or click below to reset directly:</p>
        <div style="text-align: center; margin: 30px 0;">
          <a href="${resetUrl}" style="background: #007bff; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold;">Reset Password</a>
        </div>
      </div>`
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log(`✅ Email sent: ${info.response}`);
  } catch (error) {
    console.error("❌ Nodemailer Error:", error.message);
    throw new Error("Failed to send reset email.");
  }
};